development:
  adapter: postgresql
  encoding: unicode
  database: letters_development
  pool: 5
  username: letters
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: letters_test
  pool: 5
  username: letters
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: letters_production
  pool: 5
  username: letters
  password:
